version: '3'

services:
  zabbix-db:
    image: postgres:latest
    container_name: zabbix-db
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    networks:
      - zabbix_network
    volumes:
      - zabbix-db-data:/var/lib/postgresql/data

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    depends_on:
      - zabbix-db
    environment:
      DB_SERVER_HOST: zabbix-db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"
    networks:
      - zabbix_network
    volumes:
      - zabbix-server-data:/var/lib/zabbix

networks:
  zabbix_network:

volumes:
  zabbix-db-data:
  zabbix-server-data:
